### ISSUE TITLE
launch problem

### ISSUE THREAD

**Issue by meguminrn** [Xyene/BNSBoost#2]
after pressing "launch" nothing happens, the ncsoft launcher does not seem to start, it does start without using bnsboost. Maybe its better to intergrate Log4net for better error handling.

**Comment by meguminrn** [comment]
Update: If I'm right it,  see  this line

"
string DefaultLauncherPath = (string) Registry.GetValue("HKEY_LOCAL_MACHINE\\SOFTWARE\\NCWest\\NCLauncher", "BaseDir", "???") + "\\ncLauncherR.exe";
"

If I understand this right, the your launcher tries to get a value from: HKEY_LOCAL_MACHINE\\SOFTWARE\\NCWest\\NCLauncher

So I tried to find this folder in regedit and didn't find it, could this be the problem why the launcher does not want to start?

**Comment by zeffy** [comment]
BNSBoost uses the registry to find your NCLauncher location, so if you have a non-typical install (i.e., copied your game directories to/from another drive or something), it won't be able to find it.

To solve this, I'd propose having fallback methods like:
- Attempting to launch via undocumented `nclauncher:` URI: `nc-launcher://?LauncherID=NCWest&CompanyID=12&GameID=BnS&LUpdateAddr=updater.nclauncher.ncsoft.com`
- Looking for NCLauncher in the default location `%ProgramFiles(x86)%\NCWest\NCLauncher`
- Looking for NCLauncher in the current directory

I think that should handle most scenarios gracefully. I would submit a PR to do this but unfortunately I'm working on another project.

Hope this helps.

**Comment by Svarogue** [comment]
I created ncwest and nclauncher directories in registry with my installpath data and problem was solved.
http://i.imgur.com/aDYSF9O.jpg
My default registry path HKEY_LOCAL_MACHINE\SOFTWARE\**Wow6432Node**\NCWest

**Comment by Xyene** [comment]
Whew, I didn't expect so many people to be using the launcher from a non-default location... this is the fifth report of this issue 😁 

@Svarogue is correct in that the easiest way to permanently fix this at the moment is to fix up your registry.

@meguminrn you should be able to specify the launch path in the UI, if you don't want to edit your registry. Better logging is definitely on the TODO, as is, of course, setting persistence. Could you also check out if running `nc-launcher://?LauncherID=NCWest&CompanyID=12&GameID=BnS&LUpdateAddr=updater.nclauncher.ncsoft.com` as @zeffy mentioned actually starts the launcher on your end? If so, that'd be a painless way to avoid all launch config issues.

Failing that, the rest of @zeffy's methods would likely eliminate most of these issues.

**Comment by zeffy** [comment]
Regarding ed9e861 you may want to use `Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86)` instead of expanding `%ProgramFiles(x86)%`, because I don't think that will work on 32 bit OS. 

Also you could try checking `Directory.GetCurrentDirectory()` or `Environment.CurrentDirectory` (not sure if there is any real difference between the two) in addition to `AppDomain.CurrentDomain.BaseDirectory`, because they can differ under certain circumstances. Like if someone made a shortcut to BNSBoost and changed the "Start in" directory.

So could be something like this:

```csharp
        private void Form_Load(object sender, EventArgs e)
        {
            string defaultLauncherPath = "unknown, please specify NCLauncherR.exe path";
            string[] searchDirs = {
                (string) Registry.GetValue("HKEY_LOCAL_MACHINE\\SOFTWARE\\NCWest\\NCLauncher", "BaseDir", null),
                Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86), "NCWest\\NCLauncher"),
                AppDomain.CurrentDomain.BaseDirectory,
                Environment.CurrentDirectory
            };
            foreach(string dir in searchDirs)
            {
                string path = Path.Combine(dir, "NCLauncherR.exe");
                if (File.Exists(path))
                {
                    defaultLauncherPath = path;
                    break;
                }
            }

            LauncherPathTextBox.Text = defaultLauncherPath;
        }
```

**Comment by meguminrn** [comment]
Hi Xyene,

Thanks to the new commit the launcher starts and works again, only problem is the dps meter, do I need to make another folder like this: https://imgur.com/a/xDygm and them put the xml inside it? xD.

because I don't get it and I cant see in your code where its trying to read the xml from this folder.

-megumin

**Comment by zeffy** [comment]
@meguminrn  BNSBoost doesn't do anything directly with the .dat files, it just redirects the official launcher to check inside the `unpatched` folder (if the files exist) instead of the ones the game uses. 

So you make a copy of the original (unmodified) .dat files in the `unpatched` folder, and then you are free to make any changes you want to the ones in the original `data` folder. I hope that makes sense.

**Comment by meguminrn** [comment]
Ohhh. I understand it now thanks!

**Comment by meguminrn** [comment]
update, 

for some reason when I start bnsboost launch, the game starts but it goes into Repairing modes? 


From what I understand is I can put my modified XML into the data folder and put the original XML file into unpatched folder which I created in Data folder, it should work then?

**Comment by zeffy** [comment]
Yes, that is correct. Although I haven't used the latest build yet, so I can't guarantee that it works as described. There was a bug when I was working on my steam_api build where the unpatched file path it looks for got built out of order (it was something like `filename.ext\unpatched\C:\blah\original dir`) and thus couldn't find the unpatched file. Don't know if that is related, though.

**Comment by Xyene** [comment]
@zeffy thanks, I'll add those additional search path sometime soon.

@meguminrn here's an image I posted in the bnsdojo thread that may confirm your understanding:

![image](https://cloud.githubusercontent.com/assets/1403503/25507362/9503717c-2b79-11e7-9e6b-dabb632b5676.png)

If you've done that and enabled the DPS meter with e.g. BNSBuddy and it still enters repairing mode, could you please upload your `log.txt` into <https://gisthub.com> or similar?

**Comment by meguminrn** [comment]
hi, Can you share the topic link of bnsdojo?

**Comment by Xyene** [comment]
@meguminrn [here you go](http://www.bladeandsouldojo.com/forums/topic/193783-bnsboost-launcher-verification-bypass/).

**Comment by Xyene** [comment]
@meguminrn I believe I've fixed the issue causing your client to start repairing in a new release, [could you check it out](https://github.com/Xyene/BNSBoost/releases/tag/1.2.0)?

**Comment by DarkhShadow** [comment]
Only just updated to version 1.2 from 1.0.1 and clicking launch does not work for me, I tried with 1.1 but it still would not, I have the launcher in the default location `C:\Program Files (x86)\NCWest\NCLauncher\NCLauncherR.exe` and BnS installed to `F:\BnS` , log file is empty and I see no reason for it to not launch anymore.
Windows 10 64bit, can get other info if required

**Comment by Kayo99** [comment]
I have the same problem as DarkhShadow...version 1.2 is still not working , i have everything in defaut directory (launcher and BNS)

**Comment by Oberleutnant** [comment]
Same. Directories are correct but when I click on Launch, BNSBoost just closes and nothing happens.

So far, only 1.0.0 worked for me. I'm running it as administrator, of course.

![image](https://cloud.githubusercontent.com/assets/28096619/25533825/36464c5e-2c32-11e7-83c3-4bf969db8d8e.png)

**Comment by zeffy** [comment]
Same is happening here, I'm looking into this.

**Comment by zeffy** [comment]
I think I may have fixed this, but I'd like to wait for @Xyene to review my changes before a new release is pushed.

**Comment by zeffy** [comment]
@DarkhShadow @Kayo99 @Oberleutnant I just posted a new release, could you try it and let me know if it fixes the issue? https://github.com/Xyene/BNSBoost/releases

**Comment by Oberleutnant** [comment]
@zeffy After clicking Launch:
![image](https://cloud.githubusercontent.com/assets/28096619/25540477/7ceedbe4-2c4b-11e7-9219-d856b81e2eea.png)

> See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

> ************** Exception Text **************
System.DllNotFoundException: Unable to load DLL 'Injector.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at BNSBoost.BNSBoostForm.NativeMethods.Launch(String lpLauncherBaseDir, String lpExtraClientFlags)
   at BNSBoost.BNSBoostForm.<>c__DisplayClass4_0.<LaunchAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BNSBoost.BNSBoostForm.<LaunchAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BNSBoost.BNSBoostForm.<LaunchButton_Click>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by zeffy** [comment]
Is Injector.dll in the same directory as BNSBoost.exe? That shouldn't be happening.

**Comment by Oberleutnant** [comment]
Of course it is.

**Comment by xKratosx** [comment]
Yes, I am getting the same thing.

**Comment by zeffy** [comment]
I think that exception was probably happening before, then (hence why the launcher never opened). Before the changes I made, any exceptions that happened when invoking Launch() were suppressed because it was ran in a separate thread. Probably going to have to wait for @Xyene to get back and see what he says.

**Comment by zeffy** [comment]
Out of curiosity, how are you running BNSBoost? Like directly from its own directory, with a shortcut, etc?

**Comment by xKratosx** [comment]
I tried both running from the directory and creating a shortcut on the desktop, same behavior.

**Comment by meguminrn** [comment]
"@meguminrn I believe I've fixed the issue causing your client to start repairing in a new release, could you check it out?"

Sorry for the late reaction, I tried the it works! Thanks!

**Comment by zeffy** [comment]
@xKratosx @Oberleutnant I think I may have figured out the issue, try downloading and installing 	
vc_redist.x86.exe from here: https://www.microsoft.com/en-us/download/details.aspx?id=48145

Apparently that exception can happen when a dll's dependencies can't be loaded (but instead of naming the dependency, it says the Injector.dll can't be found, pretty cryptic...)

**Comment by xKratosx** [comment]
I installed it and still getting the same error.

**Comment by zeffy** [comment]
@xKratosx Do these files exist on your PC? (assuming 64 bit OS)

- `C:\Windows\SysWOW64\ucrtbased.dll`
- `C:\Windows\SysWOW64\vcruntime140d.dll`

**Comment by meguminrn** [comment]
Just a tip/question



, instead of hard coding all the paths, why not make it more user-friendly and make a small installer where you have to locate your bns folder and the launcher in the installer it self and save it into another file. I don't know if this is a good way to do this.

**Comment by xKratosx** [comment]
ucrtbase.dll <---missing the d unless that was typo
vcruntime140.dll<---also missing the d unless typo

**Comment by zeffy** [comment]
@xKratosx Not a typo! That would explain the problem. You're probably missing a VC redistributable package, I'll try to figure out where to get them from.

**Comment by zeffy** [comment]
Also @meguminrn we don't hardcode either paths, it tries to find them from the registry, and it also looks in the default install locations. You can change the locations if you want and it should save as long as you press Launch! after changing them.

**Comment by xKratosx** [comment]
This is what I've got if it helps:
![image](https://cloud.githubusercontent.com/assets/28158233/25542264/6ac8272e-2c17-11e7-8b62-220915c5594f.png)

**Comment by zeffy** [comment]
@xKratosx Okay I figured it out. It looks like Injector.dll and Agent.dll were built in Debug mode, which is why they are trying to load those DLLs (note the `d` suffix). Which would explain why it works fine for me and others who probably have a VC development environment set up most likely.

I'll rebuild them in Release mode and swap out the zip on the releases page, give me a few minutes please.

**Comment by zeffy** [comment]
@xKratosx @Oberleutnant I'm having issues getting the dlls to compile/work in Release mode, so @Xyene will need to figure this out when he gets back. Sorry you guys are having trouble getting it working.

**Comment by xKratosx** [comment]
@zeffy no worries, thanks for trying!

**Comment by meguminrn** [comment]
@xKratosx Maybe if you downlaod https://www.visualstudio.com/vs/whatsnew/ it will work like @zeffy  explained.

**Comment by zeffy** [comment]
It may, but I don't think downloading a huge IDE like Visual Studio is a viable solution to this issue for most people! :stuck_out_tongue:

**Comment by xKratosx** [comment]
Yeah, roughly 10+GB, i'll have to pass and hope for a release mode zip.

**Comment by Kayo99** [comment]
Yea i have same errors as @xKratosx

**Comment by meguminrn** [comment]
I try to compile it but meh doesn't work: http://prntscr.com/f1zqps 

@zeffy  You have the same problem or is it just me?

**Comment by zeffy** [comment]
@meguminrn Yes that happened to me, but I fixed that by changing the Windows SDK Version version to 10.0.14393.0 because I have VS 2017. I think it was on 8.1 because Xyene has VS 2015. I also had to change the linker additional dependencies to include Shlwapi.lib, but even then when I got it to compile it still made NC Launcher crash when I pressed launch.

**Comment by Xyene** [comment]
Wait... not everybody has debug libs installed? /shy

Sorry about that @xKratosx @Kayo99 @Oberleutnant and anyone else affected by this issue, I've updated the release to include a release build that should not be linking any debug libs. Make sure to download the `-RELEASE` archive.

**Comment by Kayo99** [comment]
@Xyene Working as intended the RELEASE archive v1.2.1 , Thank you

**Comment by xKratosx** [comment]
Works great! Thanks @Xyene

**Comment by DarkhShadow** [comment]
Working for me as well, but will there be an option to re-add the unattended option? (I use a sound pack)

**Comment by Gourxis** [comment]
@Xyene still got the same problem here on -RELEASE version, when i click launch a debug message appears

**Comment by zeffy** [comment]
@DarkhShadow What does -UNATTENDED do for sound packs? Does it disable the popup messages when you open BnS or something?

**Comment by zeffy** [comment]
I added it as a default flag, so no check box is needed to enable it. Perhaps at some point we could make it optional, but I'm not really sure why that would be necessary tbh.

**Comment by Xyene** [comment]
@Gourxis could you provide us with the text of the message? Additionally, it would be helpful if you could paste the contents of your `log.txt` to a paste service like <https://gisthub.com>. Thanks!

**Comment by Gourxis** [comment]
@Xyene 
`See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: You cannot create a file already correlated.

   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   em BNSBoost.BNSBoostForm.<LaunchButton_Click>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   em System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)`

**Comment by Xyene** [comment]
@Gourxis thanks, [try this](https://ci.appveyor.com/project/Xyene/bnsboost/build/artifacts) and see if it works.

**Comment by Gourxis** [comment]
@Xyene Working now, thanks.

**Comment by iluvlamastaf** [comment]
Hey there. Everything seems to be working well except for the BnS client is still repairing my edited xml files (want to enable DPS meter). I did the unpatched folder (with the UNedited) and replaced all of the original ones with the edited ones. Any ideas?

**Comment by meguminrn** [comment]
@iluvlamastaf

You need to create a folder called: unpatched like this: http://prntscr.com/f27h0s

You need to put the original config.dat and xml.dat in this folder, after you did this,
you will need to keep another config and xml in to the base folder which you enabled dps meter on. you can just copy the config.data file and put it on the base folder and another one into the unpatched folder

**Comment by Xyene** [comment]
@iluvlamastaf if you've followed @meguminrn's advice and it continues to not work, could you provide me with the `log.txt` generated in the same directory as `BNSBoost.exe`?
